### ISSUE TITLE
生成错误的解密数据

### ISSUE THREAD

**Issue by kin9-0rz** [mikusjelly/dexsim#7]
样本：III.apk
```
[{"className": "com.android.ilIiliij", "methodName": "lIjjijII", "arguments": ["[B:[None]"], "id": "ab7806986a8efec444d44aa9a900ee0901a810c212501ea44b46ac662a1b6c7a"}]
```

```
E/AndroidRuntime(21142): Process: me.mikusjelly.dss, PID: 21142
E/AndroidRuntime(21142): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected an int but was STRING at line 1 column 2 path $[0]
E/AndroidRuntime(21142):        at com.google.gson.Gson.fromJson(Gson.java:873)
E/AndroidRuntime(21142):        at com.google.gson.Gson.fromJson(Gson.java:826)
E/AndroidRuntime(21142):        at com.google.gson.Gson.fromJson(Gson.java:775)
E/AndroidRuntime(21142):        at com.google.gson.Gson.fromJson(Gson.java:747)
E/AndroidRuntime(21142):        at me.mikusjelly.dss.DSService.buildTarget(DSService.java:292)
E/AndroidRuntime(21142):        at me.mikusjelly.dss.DSService.loadTargetsFromFile(DSService.java:209)
E/AndroidRuntime(21142):        at me.mikusjelly.dss.DSService.dss(DSService.java:154)
E/AndroidRuntime(21142):        at me.mikusjelly.dss.DSService.access$000(DSService.java:60)
E/AndroidRuntime(21142):        at me.mikusjelly.dss.DSService$TaskThread.run(DSService.java:98)
E/AndroidRuntime(21142): Caused by: java.lang.IllegalStateException: Expected an int but was STRING at line 1 column 2 path $[0]
E/AndroidRuntime(21142):        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1201)
E/AndroidRuntime(21142):        at com.google.gson.internal.bind.TypeAdapters$5.read(TypeAdapters.java:202)
E/AndroidRuntime(21142):        at com.google.gson.internal.bind.TypeAdapters$5.read(TypeAdapters.java:194)
E/AndroidRuntime(21142):        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
E/AndroidRuntime(21142):        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
E/AndroidRuntime(21142):        at com.google.gson.Gson.fromJson(Gson.java:861)
E/AndroidRuntime(21142):        ... 8 more
```

1、dexsim 处理None的时候，出现问题。
2、DSS在转换时，如果遇到异常，应该捕获，而不是崩溃。https://github.com/mikusjelly/DSS/issues/4

**Comment by kin9-0rz** [comment]
已修复
